{% set version = "0.12.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggalluvial
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggalluvial_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggalluvial/ggalluvial_{{ version }}.tar.gz
  sha256: 032e5959be201df54b19ebe2bc2e3f900a48375cdd0b517594dd8fd75fb26a56

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
    - r-dplyr >=0.7.0
    - r-ggplot2 >=2.2.0
    - r-lazyeval
    - r-rlang
    - r-tidyr >=0.7.0
    - r-tidyselect
  run:
    - r-base
    - r-dplyr >=0.7.0
    - r-ggplot2 >=2.2.0
    - r-lazyeval
    - r-rlang
    - r-tidyr >=0.7.0
    - r-tidyselect

test:
  commands:
    - $R -e "library('ggalluvial')"           # [not win]
    - "\"%R%\" -e \"library('ggalluvial')\""  # [win]

about:
  home: https://cloud.r-project.org/package=ggalluvial
  doc_url: https://corybrunson.github.io/ggalluvial/
  license: GPL-3.0-only
  summary: Alluvial diagrams use x-splines, sometimes augmented with stacked histograms, to visualize multi-dimensional or repeated-measures data with categorical or ordinal variables. They can be viewed as simplified and standardized Sankey diagrams; see Riehmann, Hanfler, and Froehlich (2005) [doi:10.1109/INFVIS.2005.1532152](https://doi.org/10.1109/INFVIS.2005.1532152)
    and Rosvall and Bergstrom (2010) [doi:10.1371/journal.pone.0008694](https://doi.org/10.1371/journal.pone.0008694). This package provides ggplot2 layers to produce alluvial diagrams from tidy data.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
  dev_url: https://github.com/corybrunson/ggalluvial/

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor
